name: githubactions
on:
   push:
     branches:
        - main
        

jobs:
      job-demo:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4


            - name: print message
              run: echo "welcome to github actions"