name: githubactions
on:
   push:
     branches:
        - main
        

jobs:
  extract:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: python e.py


  transform:
        needs: extract
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: python t.py


  load:
        needs: transform
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: python l.py
            